### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Bartelli** [stevie910/drax#13]
I stumbled upon Drax and I love it. However, I have no idea of how to use it if I download it from GitHub. Do I need to compile it? And if so, where can I find the info about how to do that?

Anyway, thanks for this great program.

**Comment by tehLuaX** [comment]
Hello, the easiest way I know is to [download the Drax archive zip file from the CodePlex Archive website](https://archive.codeplex.com/?p=drax). The (latest) installer file is located on releases\1\. All you have to do is add ".msi" to the end of the filename in order to run it.

**Comment by Beman2019** [comment]
How Do i install Brax on my windows 10 computer? It looks great

**Comment by Beman2019** [comment]
Sorry Drax. Rushing here

**Comment by g2mXagent** [comment]
here:
https://www.youtube.com/watch?v=A2GUHMrL20M

**Comment by stevie910** [comment]
Please find releases of Drax [here](https://github.com/stevie910/drax/releases). The current version is [1.6.5.0](https://github.com/stevie910/drax/releases/download/v1.6.5.0/Drax1650.msi).
