### ISSUE TITLE
Adding chapters error: time of the chapter exceeds the duration of the movie

### ISSUE THREAD

**Issue by tuthanhle** [stevie910/drax#15]
Hi there,
I have to add chapters to 30+ .mp4-files for a television program (university coursework), but for some files I get an error when I want to add a chapter: The time of the chapter exceeds the duration of the movie.

Does anybody knows how to work around this? All other .mp4-files work out fine.

Thanks!

**Comment by stevie910** [comment]
Hi @tuthanhle ,
Can you please check the last chapters timestamps of the movie? Probably one or more timestamps are beyond the length of the movie. Try deleting the last chapters timestamps step-by-step.

**Comment by tuthanhle** [comment]
Hi! Thanks for the recommendation but there are no timestamps at all. I solved the issue by converting the mp4 file in VLC to mp4.
